openapi: 3.0.0
tags:
  - name: Auth
    description: Authentication endpoints
paths:
  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login to the system
      description: Authenticate admin or superadmin user
      security: []  # No authentication required
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: admin@admin.com
                password:
                  type: string
                  format: password
                  example: admin123
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  admin:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
                        enum: [admin, superadmin]
        '401':
          description: Invalid credentials
        '500':
          description: Server error

  /api/auth/logout:
    post:
      tags:
        - Auth
      summary: Logout from the system
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully logged out
        '401':
          description: Unauthorized

  /api/auth/admin:
    post:
      tags:
        - Auth
      summary: Create new admin account (Superadmin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                role:
                  type: string
                  enum: [admin, superadmin]
                  default: admin
                password:
                  type: string
                  format: password
      responses:
        '201':
          description: Admin created successfully
        '403':
          description: Not authorized
        '500':
          description: Server error